name: tdmpc2
channels:
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.7
  - glew=2.1.0
  - glib=2.68.4
  - pip=21.0
  - python=3.10.0
  - pytorch[version='>=2.2.2']
  - torchvision[version='>=0.16.2']
  - gymnasium=0.28.1
  - jsbsim=1.1.13
  - tensorboard
  - wandb
  - pandas
prefix: /home/david/misc_software/miniconda3/envs/tdmpc2
