name: fw-310
channels:
  - conda-forge
  - defaults
dependencies:
  - glew=2.2.0
  - glib=2.78.4
  - pip=24.0
  - python=3.10
  - pytorch-cuda=12.4
  - pytorch=2.6.0.dev20241112
  - torchvision=0.15.2
  - plotly
  - matplotlib
  - numpy
  - pandas
  - jsbsim
  - seaborn
prefix: /opt/anaconda3/envs/fw-310
