name: tdmpc2
channels:
  - pytorch-nightly
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - aom=3.5.0=h27087fc_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - blas=2.116=mkl
  - blas-devel=3.9.0=16_linux64_mkl
  - brotli-python=1.1.0=py310hc6cd4ac_1
  - bzip2=1.0.8=hd590300_5
  - c-ares=1.34.3=hb9d3cd8_1
  - ca-certificates=2024.8.30=hbcca054_0
  - certifi=2024.8.30=pyhd8ed1ab_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - click=8.1.7=unix_pyh707e725_0
  - cloudpickle=3.0.0=pyhd8ed1ab_0
  - cuda-cudart=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.4.99=0
  - cuda-runtime=12.1.0=0
  - cudatoolkit=11.7.0=hd8887f6_10
  - docker-pycreds=0.4.0=py_0
  - expat=2.6.2=h59595ed_0
  - farama-notifications=0.0.4=pyhd8ed1ab_0
  - filelock=3.13.1=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_1
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.12.1=h267a509_2
  - gettext=0.21.1=h27087fc_0
  - gitdb=4.0.11=pyhd8ed1ab_0
  - glew=2.1.0=h9c3ff4c_2
  - glib=2.68.4=h9c3ff4c_1
  - glib-tools=2.68.4=h9c3ff4c_1
  - gmp=6.3.0=h59595ed_1
  - gmpy2=2.1.2=py310h3ec546c_1
  - gnutls=3.7.9=hb077bed_0
  - grpcio=1.62.2=py310h1b8f574_0
  - gymnasium=0.28.1=py310hfdc917e_0
  - icu=73.2=h59595ed_0
  - idna=3.6=pyhd8ed1ab_0
  - jax-jumpy=1.0.0=pyhd8ed1ab_0
  - jinja2=3.1.3=pyhd8ed1ab_0
  - jsbsim=1.1.13=py310hd8f1fbe_0
  - lame=3.100=h166bdaf_1003
  - lcms2=2.16=hb7c19ff_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - lerc=4.0.0=h27087fc_0
  - libabseil=20240116.2=cxx17_he02047a_1
  - libblas=3.9.0=16_linux64_mkl
  - libcblas=3.9.0=16_linux64_mkl
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.9.0.20=0
  - libcurand=10.3.5.119=0
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libdeflate=1.19=hd590300_0
  - libdrm=2.4.120=hd590300_0
  - libexpat=2.6.2=h59595ed_0
  - libffi=3.4.2=h7f98852_5
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgfortran-ng=13.2.0=h69a702a_5
  - libgfortran5=13.2.0=ha4646dd_5
  - libglib=2.68.4=h174f98d_1
  - libglu=9.0.0=hac7e632_1003
  - libgrpc=1.62.2=h15f2491_0
  - libhwloc=2.9.3=default_h554bfaf_1009
  - libiconv=1.17=hd590300_2
  - libidn2=2.3.7=hd590300_0
  - libjpeg-turbo=3.0.0=hd590300_1
  - liblapack=3.9.0=16_linux64_mkl
  - liblapacke=3.9.0=16_linux64_mkl
  - libnpp=12.0.2.50=0
  - libnsl=2.0.1=hd590300_0
  - libnvjitlink=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libopus=1.3.1=h7f98852_1
  - libpciaccess=0.18=hd590300_0
  - libpng=1.6.43=h2797004_0
  - libprotobuf=4.25.3=h08a7969_0
  - libre2-11=2023.09.01=h5a48ba9_2
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-ng=13.2.0=h7e041cc_5
  - libtasn1=4.19.0=h166bdaf_0
  - libtiff=4.6.0=ha9c0a0a_2
  - libunistring=0.9.10=h7f98852_0
  - libuuid=2.38.1=h0b41bf4_0
  - libva=2.21.0=hd590300_0
  - libvpx=1.11.0=h9c3ff4c_3
  - libwebp-base=1.3.2=hd590300_0
  - libxcb=1.15=h0b41bf4_0
  - libxml2=2.12.6=h232c23b_0
  - libzlib=1.2.13=hd590300_5
  - llvm-openmp=15.0.7=h0cdce71_0
  - markdown=3.6=pyhd8ed1ab_0
  - markupsafe=2.1.5=py310h2372a71_0
  - mkl=2022.1.0=h84fe81f_915
  - mkl-devel=2022.1.0=ha770c72_916
  - mkl-include=2022.1.0=h84fe81f_915
  - mpc=1.3.1=hfe3b2da_0
  - mpfr=4.2.1=h9458935_0
  - mpmath=1.3.0=pyhd8ed1ab_0
  - ncurses=6.4=h59595ed_2
  - nettle=3.9.1=h7ab15ed_0
  - networkx=3.2.1=pyhd8ed1ab_0
  - openh264=2.3.1=hcb278e6_2
  - openjpeg=2.5.2=h488ebb8_0
  - openssl=3.4.0=hb9d3cd8_0
  - p11-kit=0.24.1=hc5aa10d_0
  - pcre=8.45=h9c3ff4c_0
  - pillow=10.2.0=py310h01dd4db_0
  - pip=21.0.1=pyhd8ed1ab_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - pymap3d=3.1.0=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.10.0=h543edf9_3_cpython
  - python-dateutil=2.9.0.post0=pyhff2d567_0
  - python-tzdata=2024.2=pyhd8ed1ab_0
  - python_abi=3.10=4_cp310
  - pytorch=2.4.0.dev20240319=py3.10_cuda12.1_cudnn8.9.2_0
  - pytorch-cuda=12.1=ha16c6d3_5
  - pytorch-mutex=1.0=cuda
  - pytz=2024.1=pyhd8ed1ab_0
  - pyyaml=6.0.1=py310h2372a71_1
  - re2=2023.09.01=h7f4b329_2
  - readline=8.2=h8228510_1
  - requests=2.31.0=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.39.2=h4ff8645_0
  - svt-av1=1.4.1=hcb278e6_0
  - sympy=1.12=pypyh9d50eac_103
  - tbb=2021.11.0=h00ab1b0_1
  - tensorboard=2.18.0=pyhd8ed1ab_0
  - tensorboard-data-server=0.7.0=py310h6c63255_2
  - tk=8.6.13=noxft_h4845f30_101
  - torchtriton=3.0.0+989adb9a29=py310
  - torchvision=0.18.0.dev20240319=py310_cu121
  - typing_extensions=4.10.0=pyha770c72_0
  - urllib3=2.2.1=pyhd8ed1ab_0
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xorg-fixesproto=5.0=h7f98852_1002
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libx11=1.8.7=h8ee46fc_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7f98852_2
  - zlib=1.2.13=hd590300_5
  - zstd=1.5.5=hfc55251_0
  - pip:
      - absl-py==2.0.0
      - addict==2.4.0
      - antlr4-python3-runtime==4.9.3
      - asttokens==2.4.1
      - attrs==23.2.0
      - blinker==1.7.0
      - cffi==1.16.0
      - comm==0.2.2
      - configargparse==1.7
      - contourpy==1.2.0
      - cycler==0.12.1
      - cython==0.29.37
      - dash==2.16.1
      - dash-core-components==2.0.0
      - dash-html-components==2.0.0
      - dash-table==5.0.0
      - decorator==4.4.2
      - dm-control==1.0.8
      - dm-env==1.6
      - dm-tree==0.1.8
      - exceptiongroup==1.2.0
      - executing==2.0.1
      - fasteners==0.19
      - fastjsonschema==2.19.1
      - ffmpeg==1.4
      - flask==3.0.2
      - fonttools==4.50.0
      - fsspec==2024.3.1
      - gitpython==3.1.42
      - glfw==2.6.4
      - gym==0.21.0
      - hydra-core==1.3.2
      - hydra-submitit-launcher==1.2.0
      - imageio==2.33.1
      - imageio-ffmpeg==0.4.9
      - importlib-metadata==7.0.2
      - ipython==8.22.2
      - ipywidgets==8.1.2
      - itsdangerous==2.1.2
      - jedi==0.19.1
      - joblib==1.3.2
      - jsonschema==4.21.1
      - jsonschema-specifications==2023.12.1
      - jupyter-core==5.7.2
      - jupyterlab-widgets==3.0.10
      - kiwisolver==1.4.5
      - kornia==0.7.1
      - labmaze==1.0.6
      - lxml==5.1.0
      - matplotlib==3.8.3
      - matplotlib-inline==0.1.6
      - moviepy==1.0.3
      - mujoco==2.3.1
      - mujoco-py==2.1.2.14
      - nbformat==5.10.3
      - nest-asyncio==1.6.0
      - numpy==1.23.5
      - omegaconf==2.3.0
      - open3d==0.18.0
      - opencv-contrib-python==4.9.0.80
      - opencv-python==4.9.0.80
      - packaging==24.0
      - pandas==2.1.4
      - parso==0.8.3
      - patchelf==0.17.2.1
      - pexpect==4.9.0
      - platformdirs==4.2.0
      - plotly==5.20.0
      - proglog==0.1.10
      - prompt-toolkit==3.0.43
      - protobuf==4.25.2
      - psutil==5.9.8
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pycparser==2.21
      - pygments==2.17.2
      - pyopengl==3.1.7
      - pyparsing==2.4.7
      - pyquaternion==0.9.9
      - referencing==0.34.0
      - retrying==1.3.4
      - rpds-py==0.18.0
      - sapien==2.2.1
      - scikit-learn==1.4.1.post1
      - scipy==1.12.0
      - sentry-sdk==1.42.0
      - setproctitle==1.3.3
      - setuptools==65.5.0
      - smmap==5.0.1
      - stack-data==0.6.3
      - submitit==1.5.1
      - tenacity==8.2.3
      - tensordict-nightly==2024.1.10
      - termcolor==2.4.0
      - threadpoolctl==3.3.0
      - torchrl-nightly==2024.1.10
      - tqdm==4.66.1
      - traitlets==5.14.2
      - transforms3d==0.4.1
      - trimesh==4.0.9
      - tzdata==2024.1
      - wandb==0.16.2
      - wcwidth==0.2.13
      - werkzeug==3.0.1
      - wheel==0.38.0
      - widgetsnbextension==4.0.10
      - zipp==3.18.1
prefix: /home/david/misc_software/miniconda3/envs/tdmpc2
