name: fw-tdmpc2-39
channels:
  - pytorch-nightly
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.8
  - attr=2.5.1
  - blas=1.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.4.26
  - cairo=1.16.0
  - certifi=2025.4.26
  - cffi=1.17.1
  - charset-normalizer=3.4.2
  - contourpy=1.3.0
  - cpython=3.9.22
  - cuda-cudart=12.4.127
  - cuda-cupti=12.4.127
  - cuda-libraries=12.4.1
  - cuda-nvrtc=12.4.127
  - cuda-nvtx=12.4.127
  - cuda-opencl=12.4.127
  - cuda-runtime=12.4.1
  - cudatoolkit=11.8.0
  - cycler=0.12.1
  - dbus=1.13.6
  - expat=2.7.0
  - fftw=3.3.10
  - filelock=3.18.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.58.0
  - freetype=2.13.3
  - gettext=0.24.1
  - gettext-tools=0.24.1
  - glew=2.2.0
  - glib=2.78.4
  - glib-tools=2.78.4
  - gmp=6.3.0
  - gmpy2=2.2.1
  - graphite2=1.3.13
  - gst-plugins-base=1.22.0
  - gstreamer=1.22.0
  - gstreamer-orc=0.4.41
  - h2=4.2.0
  - harfbuzz=6.0.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=70.1
  - idna=3.10
  - importlib-resources=6.5.2
  - importlib_resources=6.5.2
  - intel-openmp=2022.0.1
  - jack=1.9.22
  - jinja2=3.1.6
  - jpeg=9e
  - keyutils=1.6.1
  - kiwisolver=1.4.7
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.15
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - libasprintf=0.24.1
  - libasprintf-devel=0.24.1
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcap=2.67
  - libcblas=3.9.0
  - libclang=15.0.7
  - libclang13=15.0.7
  - libcublas=12.4.5.8
  - libcufft=11.2.1.3
  - libcufile=1.9.1.3
  - libcups=2.3.3
  - libcurand=10.3.5.147
  - libcusolver=11.6.1.9
  - libcusparse=12.3.1.170
  - libdb=6.2.32
  - libdeflate=1.17
  - libedit=3.1.20250104
  - libevent=2.1.10
  - libexpat=2.7.0
  - libffi=3.4.6
  - libflac=1.4.3
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgcrypt=1.11.1
  - libgcrypt-devel=1.11.1
  - libgcrypt-lib=1.11.1
  - libgcrypt-tools=1.11.1
  - libgettextpo=0.24.1
  - libgettextpo-devel=0.24.1
  - libgfortran=15.1.0
  - libgfortran-ng=15.1.0
  - libgfortran5=15.1.0
  - libglib=2.78.4
  - libglu=9.0.0
  - libgomp=15.1.0
  - libgpg-error=1.55
  - libiconv=1.18
  - liblapack=3.9.0
  - libllvm15=15.0.7
  - libltdl=2.4.3a
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnpp=12.2.5.30
  - libnsl=2.0.1
  - libnvfatbin=12.4.127
  - libnvjitlink=12.4.127
  - libnvjpeg=12.3.1.117
  - libogg=1.3.5
  - libopus=1.5.2
  - libpng=1.6.47
  - libpq=15.3
  - libsndfile=1.2.2
  - libsqlite=3.49.2
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libsystemd0=253
  - libtiff=4.5.0
  - libtool=2.5.4
  - libudev1=253
  - libuuid=2.38.1
  - libvorbis=1.3.7
  - libwebp-base=1.5.0
  - libxcb=1.13
  - libxcrypt=4.4.36
  - libxkbcommon=1.5.0
  - libxml2=2.10.3
  - libzlib=1.3.1
  - llvm-openmp=15.0.7
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - matplotlib=3.9.1
  - matplotlib-base=3.9.1
  - mkl=2022.1.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpg123=1.32.9
  - mpmath=1.3.0
  - munkres=1.1.4
  - mysql-common=8.0.33
  - mysql-libs=8.0.33
  - narwhals=1.40.0
  - ncurses=6.5
  - networkx=3.2.1
  - nspr=4.36
  - nss=3.111
  - openjpeg=2.5.0
  - openssl=3.1.8
  - packaging=25.0
  - pcre2=10.43
  - pillow=9.4.0
  - pip=24.0
  - pixman=0.46.0
  - plotly=6.1.0
  - ply=3.11
  - pthread-stubs=0.4
  - pulseaudio=16.1
  - pulseaudio-client=16.1
  - pulseaudio-daemon=16.1
  - pycparser=2.22
  - pyparsing=3.2.3
  - pyqt=5.15.9
  - pyqt5-sip=12.12.2
  - pysocks=1.7.1
  - python=3.9.18
  - python-dateutil=2.9.0.post0
  - python_abi=3.9
  - pytorch=2.6.0.dev20241112
  - pytorch-cuda=12.4
  - pytorch-mutex=1.0
  - pyyaml=6.0.2
  - qhull=2020.2
  - qt-main=5.15.8
  - readline=8.2
  - requests=2.32.3
  - setuptools=80.1.0
  - sip=6.7.12
  - six=1.17.0
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.2.1
  - torchtriton=3.1.0+cf34004b8a
  - torchvision=0.15.2
  - tornado=6.5
  - typing_extensions=4.13.2
  - unicodedata2=16.0.0
  - urllib3=2.4.0
  - wheel=0.45.1
  - xcb-util=0.4.0
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil=0.3.9
  - xcb-util-wm=0.4.1
  - xkeyboard-config=2.38
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.4
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - yaml=0.2.5
  - zipp=3.21.0
  - zstandard=0.23.0
  - zstd=1.5.7
  - pip:
      - absl-py==2.2.2
      - antlr4-python3-runtime==4.9.3
      - click==8.1.8
      - cloudpickle==3.1.1
      - cython==3.1.1
      - decorator==4.4.2
      - dm-control==1.0.16
      - dm-env==1.6
      - dm-tree==0.1.8
      - docker-pycreds==0.4.0
      - etils==1.5.2
      - farama-notifications==0.0.4
      - ffmpeg==1.4
      - fsspec==2025.3.2
      # - fw-flightcontrol==0.0.1
      # - fw-jsbgym==0.0.1
      - gitdb==4.0.12
      - gitpython==3.1.44
      - glfw==2.7.0
      - gymnasium==0.29.1
      - h5py==3.11.0
      - hydra-core==1.3.2
      - hydra-submitit-launcher==1.2.0
      - imageio==2.34.1
      - imageio-ffmpeg==0.4.9
      - importlib-metadata==8.7.0
      # - jsbsim==1.2.3.dev1
      - kornia==0.7.2
      - kornia-rs==0.1.9
      - labmaze==1.0.6
      - lxml==5.4.0
      - moviepy==1.0.3
      - mujoco==3.1.2
      - numpy==1.24.4
      - omegaconf==2.3.0
      - orjson==3.10.18
      - pandas==2.0.3
      - platformdirs==4.3.8
      - proglog==0.1.12
      - protobuf==5.29.4
      - psutil==7.0.0
      - pyopengl==3.1.9
      - pytz==2025.2
      - scipy==1.13.1
      - sentry-sdk==2.28.0
      - setproctitle==1.3.6
      - smmap==5.0.2
      - submitit==1.5.1
      - sympy==1.13.1
      - tensordict-nightly==2025.1.1
      - termcolor==2.4.0
      - torchrl-nightly==2025.1.1
      - tqdm==4.66.4
      - tzdata==2025.2
      - wandb==0.17.4
prefix: /opt/anaconda3/envs/tdmpc2-mod
